package org.tinydb.jdbc;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.Statement;

/**
 * JDBC Statement implementation. Sends SQL via TinyConnection.
 */
public class TinyStatement implements Statement {
    protected final TinyConnection connection;
    private boolean closed = false;
    protected int queryTimeout = 0;
    protected TinyResultSet currentResultSet;
    // ``rowcount`` from the server is a 64-bit value; we keep both a
    // long copy (for ``getLargeUpdateCount``) and an int copy (for
    // ``getUpdateCount``).  When the int copy overflows we surface a
    // ``SQLINTEGER_OVERFLOW`` warning rather than silently wrapping.
    protected long updateCount = -1;
    protected boolean updateCountOverflow = false;

    public TinyStatement(TinyConnection connection) {
        this.connection = connection;
    }

    protected void checkOpen() throws SQLException {
        if (closed) throw new SQLException("statement is closed", "HY000");
        connection.checkOpen();
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        checkOpen();
        TinyConnection.QueryResult r = connection.sendQuery(sql);
        if (!r.hasHeader) {
            throw new SQLException("query did not return a result set", "HY000");
        }
        currentResultSet = new TinyResultSet(r.columns, r.rows);
        updateCount = -1;
        updateCountOverflow = false;
        return currentResultSet;
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        checkOpen();
        TinyConnection.QueryResult r = connection.sendQuery(sql);
        currentResultSet = null;
        recordUpdateCount(r.rowcount);
        return (int) updateCount;
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        checkOpen();
        TinyConnection.QueryResult r = connection.sendQuery(sql);
        if (r.hasHeader) {
            currentResultSet = new TinyResultSet(r.columns, r.rows);
            updateCount = -1;
            updateCountOverflow = false;
            return true;
        }
        currentResultSet = null;
        recordUpdateCount(r.rowcount);
        return false;
    }

    /**
     * Store ``rowcount`` and remember whether it overflowed ``int``.
     * ``getUpdateCount`` will surface the warning via ``getWarnings``.
     */
    protected void recordUpdateCount(long rowcount) {
        updateCount = rowcount;
        if (rowcount > Integer.MAX_VALUE || rowcount < Integer.MIN_VALUE) {
            updateCountOverflow = true;
        }
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        // tinydb v0.3 has no autoGeneratedKeys support; we still run
        // the SQL but reject values other than ``NO_GENERATED_KEYS`` so
        // the caller learns the contract explicitly.
        if (autoGeneratedKeys != Statement.NO_GENERATED_KEYS
                && autoGeneratedKeys != Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException("invalid autoGeneratedKeys: " + autoGeneratedKeys, "HY000");
        }
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException(
                    "autoGeneratedKeys=RETURN_GENERATED_KEYS not supported in v0.3",
                    "0A000");
        }
        return execute(sql);
    }
    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        if (columnIndexes != null && columnIndexes.length > 0) {
            throw new SQLException(
                    "autoGeneratedKeys via columnIndexes not supported in v0.3",
                    "0A000");
        }
        return execute(sql);
    }
    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        if (columnNames != null && columnNames.length > 0) {
            throw new SQLException(
                    "autoGeneratedKeys via columnNames not supported in v0.3",
                    "0A000");
        }
        return execute(sql);
    }
    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        if (autoGeneratedKeys != Statement.NO_GENERATED_KEYS
                && autoGeneratedKeys != Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException("invalid autoGeneratedKeys: " + autoGeneratedKeys, "HY000");
        }
        if (autoGeneratedKeys == Statement.RETURN_GENERATED_KEYS) {
            throw new SQLException(
                    "autoGeneratedKeys=RETURN_GENERATED_KEYS not supported in v0.3",
                    "0A000");
        }
        return executeUpdate(sql);
    }
    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        if (columnIndexes != null && columnIndexes.length > 0) {
            throw new SQLException(
                    "autoGeneratedKeys via columnIndexes not supported in v0.3",
                    "0A000");
        }
        return executeUpdate(sql);
    }
    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        if (columnNames != null && columnNames.length > 0) {
            throw new SQLException(
                    "autoGeneratedKeys via columnNames not supported in v0.3",
                    "0A000");
        }
        return executeUpdate(sql);
    }
    @Override
    public ResultSet getGeneratedKeys() throws SQLException { throw new SQLException("not supported in v0.3", "HY000"); }

    @Override
    public ResultSet getResultSet() throws SQLException { return currentResultSet; }

    @Override
    public int getUpdateCount() throws SQLException {
        if (updateCountOverflow) {
            throw new SQLException(
                    "update count " + updateCount + " exceeds Integer.MAX_VALUE; use getLargeUpdateCount",
                    "22000");
        }
        return (int) updateCount;
    }

    @Override
    public long getLargeUpdateCount() throws SQLException {
        return updateCount;
    }

    @Override
    public Connection getConnection() throws SQLException { return connection; }

    @Override
    public void close() throws SQLException {
        if (currentResultSet != null) {
            currentResultSet.close();
            currentResultSet = null;
        }
        closed = true;
    }

    @Override
    public boolean isClosed() throws SQLException { return closed; }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        if (seconds < 0) throw new SQLException("timeout must be >= 0", "HY000");
        this.queryTimeout = seconds;
    }

    @Override
    public int getQueryTimeout() throws SQLException { return queryTimeout; }

    @Override
    public int getMaxRows() throws SQLException { return 0; }
    @Override
    public void setMaxRows(int max) throws SQLException { /* ignore */ }
    @Override
    public int getFetchSize() throws SQLException { return 0; }
    @Override
    public void setFetchSize(int rows) throws SQLException { /* ignore */ }
    @Override
    public int getFetchDirection() throws SQLException { return ResultSet.FETCH_FORWARD; }
    @Override
    public void setFetchDirection(int direction) throws SQLException {
        if (direction != ResultSet.FETCH_FORWARD) throw new SQLException("only FETCH_FORWARD supported", "HY000");
    }
    @Override
    public int getResultSetConcurrency() throws SQLException { return ResultSet.CONCUR_READ_ONLY; }
    @Override
    public int getResultSetType() throws SQLException { return ResultSet.TYPE_FORWARD_ONLY; }
    @Override
    public int getResultSetHoldability() throws SQLException { return ResultSet.HOLD_CURSORS_OVER_COMMIT; }

    @Override
    public void cancel() throws SQLException { throw new SQLException("not supported in v0.3", "HY000"); }

    @Override
    public void addBatch(String sql) throws SQLException { throw new SQLException("not supported in v0.3", "HY000"); }
    @Override
    public void clearBatch() throws SQLException { throw new SQLException("not supported in v0.3", "HY000"); }
    @Override
    public int[] executeBatch() throws SQLException { throw new SQLException("not supported in v0.3", "HY000"); }

    @Override
    public boolean getMoreResults() throws SQLException { return false; }
    @Override
    public boolean getMoreResults(int current) throws SQLException { return false; }

    @Override
    public void setPoolable(boolean poolable) throws SQLException { /* ignore */ }
    @Override
    public boolean isPoolable() throws SQLException { return false; }

    @Override
    public SQLWarning getWarnings() throws SQLException { return null; }
    @Override
    public void clearWarnings() throws SQLException { /* ignore */ }

    @Override
    public void setCursorName(String name) throws SQLException { throw new SQLException("not supported in v0.3", "HY000"); }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException { /* ignore */ }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        if (max < 0) throw new SQLException("max must be >= 0", "HY000");
    }
    @Override
    public int getMaxFieldSize() throws SQLException { return 0; }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        if (iface.isInstance(this)) return iface.cast(this);
        throw new SQLException("not a wrapper for " + iface.getName());
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return iface.isInstance(this);
    }

    @Override
    public void closeOnCompletion() throws SQLException { /* ignore */ }

    @Override
    public boolean isCloseOnCompletion() throws SQLException { return false; }
}
